// ─── Mock data — vervang dit stap voor stap met echte Supabase data ──────────
// Zolang je .env nog niet ingevuld is, werkt de app met deze data.

export const MOCK_LEADS = [
  {
    id: 'peter',
    name: 'Peter Willems',
    initials: 'PW',
    avatar_class: 'av-amber',
    company: 'Willems & Zn',
    status: 'hot',
    prev_status: 'hot',
    channel: 'whatsapp',
    date_label: 'Vandaag',
    summary: 'Demo ingepland wo 23 apr',
    ai_mode: true,
    esc_count: 0,
    memory: { Naam: 'Peter Willems', Bedrijf: 'Willems & Zn', Status: 'Hot lead', Behoefte: 'Demo' },
    messages: [
      { id: 1, direction: 'in',  text: 'Hallo, ik wil graag een demo zien.',       ts: '12:50', ai: false },
      { id: 2, direction: 'out', text: 'Hoi Peter! Wanneer schikt het?',            ts: '12:51', ai: true  },
      { id: 3, direction: 'in',  text: 'Woensdag 10:00 is prima.',                  ts: '13:18', ai: false },
      { id: 4, direction: 'out', text: 'Demo bevestigd wo 23 apr om 10:00!',        ts: '13:19', ai: true  },
    ],
  },
  {
    id: 'mark',
    name: 'Mark Kuiper',
    initials: 'MK',
    avatar_class: 'av-red',
    company: 'Kuiper Logistics',
    status: 'esc',
    prev_status: 'warm',
    channel: 'whatsapp',
    date_label: 'Vandaag',
    summary: 'Maatwerk offerte 3 locaties',
    ai_mode: false,
    esc_count: 1,
    memory: { Naam: 'Mark Kuiper', Bedrijf: 'Kuiper Logistics', Status: 'Escalatie', Behoefte: 'Maatwerk offerte' },
    messages: [
      { id: 1, direction: 'in',  text: 'Ik wil iets op maat voor 3 locaties.',      ts: '14:33', ai: false },
      { id: 2, direction: 'out', text: 'Ik zet dit door naar een collega!',          ts: '14:34', ai: true  },
      { id: 3, direction: 'in',  text: 'Kan ik één offerte voor alles?',             ts: '14:47', ai: false },
      { id: 4, direction: 'sys', text: 'AI kon dit niet beantwoorden — geëscaleerd', ts: '',      ai: false },
    ],
  },
  {
    id: 'jan',
    name: 'Jan de Boer',
    initials: 'JD',
    avatar_class: 'av-purple',
    company: 'De Boer Retail',
    status: 'warm',
    prev_status: 'warm',
    channel: 'whatsapp',
    date_label: 'Vandaag',
    summary: 'Prijsvraag pakket M',
    ai_mode: true,
    esc_count: 0,
    memory: { Naam: 'Jan de Boer', Bedrijf: 'De Boer Retail', Status: 'Warm lead', Behoefte: 'Pakket M' },
    messages: [
      { id: 1, direction: 'in',  text: 'Wat kost pakket M voor 8 personen?', ts: '10:55', ai: false },
      { id: 2, direction: 'out', text: 'Pakket M is €99/mnd. Jaarlijks: €990.', ts: '10:57', ai: true },
    ],
  },
  {
    id: 'lisa',
    name: 'Lisa Hendriks',
    initials: 'LH',
    avatar_class: 'av-blue',
    company: 'Rotterdam',
    status: 'cold',
    prev_status: 'cold',
    channel: 'whatsapp',
    date_label: 'Vandaag',
    summary: 'Leveringstijd gevraagd',
    ai_mode: true,
    esc_count: 0,
    memory: { Naam: 'Lisa Hendriks', Bedrijf: '—', Status: 'Koud contact', Behoefte: 'Leveringsinfo' },
    messages: [
      { id: 1, direction: 'in',  text: 'Hoe lang duurt levering naar Rotterdam?', ts: '09:28', ai: false },
      { id: 2, direction: 'out', text: '2-3 werkdagen. Spoed: +€15.',             ts: '09:29', ai: true  },
    ],
  },
  {
    id: 'rosa',
    name: 'Rosa Bakker',
    initials: 'RB',
    avatar_class: 'av-green',
    company: 'Instagram',
    status: 'new',
    prev_status: 'new',
    channel: 'whatsapp',
    date_label: 'Vandaag',
    summary: 'Eerste contact via Instagram',
    ai_mode: true,
    esc_count: 0,
    memory: { Naam: 'Rosa Bakker', Bedrijf: '—', Status: 'Nieuw', Behoefte: 'Onbekend' },
    messages: [
      { id: 1, direction: 'in',  text: 'Hoi! Ik zag jullie via Instagram.',          ts: '08:15', ai: false },
      { id: 2, direction: 'out', text: 'Hoi Rosa! Waarmee kan ik je helpen?',        ts: '08:16', ai: true  },
    ],
  },
]

export const MOCK_EMAILS = [
  {
    id: 'thomas',
    name: 'Thomas Klein',
    initials: 'TK',
    avatar_class: 'av-purple',
    company: 'bedrijf.nl',
    status: 'hot',
    date_label: 'Gisteren',
    subject: 'Interesse in samenwerking 2025',
    body: 'Goedemiddag,\n\nWe hebben jullie aanbod bekeken en willen graag verder praten over een samenwerking voor 2025.\n\nMet vriendelijke groet,\nThomas Klein',
    draft: 'Hallo Thomas,\n\nBedankt voor je bericht! Fijn om te horen dat jullie interesse hebben.\n\nIk heb volgende week dinsdag of woensdag beschikbaar voor een kennismakingsgesprek. Wanneer schikt het jou?\n\nMet vriendelijke groet,\n[Jouw naam]',
    filtered: false,
    draft_status: null,
  },
  {
    id: 'adam',
    name: 'A. van Dam',
    initials: 'AV',
    avatar_class: 'av-teal',
    company: 'startup.io',
    status: 'warm',
    date_label: 'Di 15 apr',
    subject: 'Vraag over API-integratie',
    body: 'Hallo,\n\nKunnen jullie API koppelen aan ons Node.js systeem?\n\nGroeten, A. van Dam',
    draft: 'Hallo,\n\nJa, we bieden een REST API aan die volledig compatible is met Node.js. Ik stuur je de documentatie zodra je akkoord gaat.\n\nMet vriendelijke groet,\n[Jouw naam]',
    filtered: false,
    draft_status: null,
  },
  {
    id: 'mol',
    name: 'N. Mol',
    initials: 'NM',
    avatar_class: 'av-blue',
    company: 'consult.nl',
    status: 'warm',
    date_label: 'Ma 14 apr',
    subject: 'Oriënterend gesprek aanvragen',
    body: 'Goedemiddag,\n\nIk kom via LinkedIn en ben benieuwd naar jullie dienstverlening.\n\nN. Mol',
    draft: 'Hallo N. Mol,\n\nLeuk dat je ons via LinkedIn gevonden hebt! We plannen graag een oriënterend gesprek in.\n\nMet vriendelijke groet,\n[Jouw naam]',
    filtered: false,
    draft_status: null,
  },
  {
    id: 'spam1',
    name: 'MailChimp Promo',
    initials: 'MC',
    avatar_class: 'av-blue',
    company: 'mailchimp.com',
    status: 'spam',
    date_label: 'Vandaag',
    subject: '50% korting op premium!',
    body: '',
    draft: '',
    filtered: true,
    draft_status: null,
  },
  {
    id: 'spam2',
    name: 'Factuur #2847',
    initials: 'FT',
    avatar_class: 'av-green',
    company: 'leverancier.nl',
    status: 'spam',
    date_label: 'Vandaag',
    subject: 'Factuur #2847 — betaling vereist',
    body: '',
    draft: '',
    filtered: true,
    draft_status: null,
  },
]

export const MOCK_WEBSITE_VISITORS = [
  {
    id: 'v1',
    name: 'Bezoeker #1',
    initials: 'V1',
    avatar_class: 'av-green',
    summary: 'Vraagt over pricing',
    ai_mode: true,
    status: 'warm',
    messages: [
      { id: 1, direction: 'in',  text: 'Hallo, wat zijn jullie pakketten?',                        ts: 'Nu', ai: false },
      { id: 2, direction: 'out', text: 'Hoi! We hebben S (€49), M (€99) en L (€199) per maand.',   ts: 'Nu', ai: true  },
      { id: 3, direction: 'in',  text: 'Hoeveel gebruikers kan pakket M aan?',                      ts: 'Nu', ai: false },
      { id: 4, direction: 'out', text: 'Pakket M is voor teams tot 15 personen.',                    ts: 'Nu', ai: true  },
    ],
  },
  {
    id: 'v2',
    name: 'Bezoeker #2',
    initials: 'V2',
    avatar_class: 'av-blue',
    summary: 'Vraag over levering',
    ai_mode: true,
    status: 'cold',
    messages: [
      { id: 1, direction: 'in',  text: 'Hoe snel wordt mijn bestelling geleverd?',                              ts: '2m', ai: false },
      { id: 2, direction: 'out', text: 'Standaard 2-3 werkdagen. Spoed voor €15 extra bij bestelling vóór 12:00.', ts: '2m', ai: true  },
    ],
  },
]

export const MOCK_KB = [
  { id: 1, category: 'product',    title: 'Pakketprijzen',  content: 'S: €49/mnd. M: €99/mnd (tot 15 personen). L: €199/mnd. Jaarlijks: 2 maanden gratis.', active: true,  updated: '17 apr' },
  { id: 2, category: 'product',    title: 'Levertijden',    content: 'Standaard 2-3 werkdagen. Spoed: +€15, zelfde dag vóór 12:00.',                        active: true,  updated: '15 apr' },
  { id: 3, category: 'support',    title: 'Retourbeleid',   content: '14 dagen retour, ongebruikt. Restitutie binnen 5 werkdagen.',                          active: true,  updated: '10 apr' },
  { id: 4, category: 'escalation', title: 'Escalatieregels',content: 'Escaleer bij: maatwerk, klacht, budget >€500, juridisch, SAP-integraties.',            active: true,  updated: '12 apr' },
  { id: 5, category: 'sales',      title: 'Demo aanvragen', content: 'Demo op werkdagen, 30 min. Via demo@bedrijf.nl of WhatsApp.',                          active: true,  updated: '14 apr' },
  { id: 6, category: 'support',    title: 'API-integratie', content: 'REST API beschikbaar. Node.js, Python, PHP. Sandbox op aanvraag.',                     active: false, updated: '8 apr'  },
]

export const MOCK_LOGS = [
  { id: 1, question: 'Wat kost pakket M?',        matched_items: 'Pakketprijzen',  escalated: false, created_at: '2026-04-17T14:52:00' },
  { id: 2, question: 'Levering Rotterdam?',        matched_items: 'Levertijden',    escalated: false, created_at: '2026-04-17T14:47:00' },
  { id: 3, question: 'Integreren met SAP?',        matched_items: '—',              escalated: true,  created_at: '2026-04-17T14:33:00' },
  { id: 4, question: 'Retour aanvragen',           matched_items: 'Retourbeleid',   escalated: false, created_at: '2026-04-17T13:20:00' },
  { id: 5, question: 'Maatwerk offerte 3 locaties',matched_items: '—',              escalated: true,  created_at: '2026-04-17T13:15:00' },
  { id: 6, question: 'Demo inplannen',             matched_items: 'Demo aanvragen', escalated: false, created_at: '2026-04-17T12:51:00' },
]
